apiVersion: v1
kind: Service
metadata:
  name: balances-app-service
  labels:
    com.job.service: balances-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 5002
      targetPort: 5002
      nodePort: 31002
  selector:
    com.job.service: balances-app
    tier: golang